#ifndef VIDEOEDITPLUGINS_GLOBAL_H
#define VIDEOEDITPLUGINS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIDEOEDITPLUGINS_LIBRARY)
#  define VIDEOEDITPLUGINSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIDEOEDITPLUGINSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIDEOEDITPLUGINS_GLOBAL_H
